# TODO: Make the trigger more strict
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
    
jobs:
  github-release:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NUGET_FEED: https://api.nuget.org/v3/index.json
      NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      #- name: Verify commit exists in origin/master
      #  run: |
      #    git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
      #    git branch --remote --contains | grep origin/master
          
      - name: Add nuget source
        run: |
          dotnet nuget add source --username binarycow --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/binarycow/index.json"

      - name: Build
        run: dotnet build --configuration Release NetworkPrimitives.sln
      - name: Test
        run: dotnet test --configuration Release --no-build NetworkPrimitives.sln
      - name: Pack
        run: dotnet pack --configuration Release --no-build --output . --include-symbols --include-source NetworkPrimitives.sln
      #- name: Push to GitHub nuget feed
      #  run: dotnet nuget push --source github --api-key ${{ secrets.GITHUB_TOKEN }} NetworkPrimitives.*.nupkg --skip-duplicate
      #- name: Push to official nuget feed
      #  run: dotnet nuget push --source $NUGET_FEED --api-key $NUGET_KEY NetworkPrimitives.*.nupkg --skip-duplicate
      - name: Create Release
        uses: ncipollo/release-action@v1.8.10
        with:
          artifacts: "NetworkPrimitives.*.nupkg"
          # bodyFile: "body.md"
          artifactErrorsFailBuild: true
          # draft: true
          omitBody: true
          prerelease: true
          tag: v1.0.0-rc2
          token: ${{ secrets.GITHUB_TOKEN }}
