# TODO: Make the trigger more strict
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  github-release:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      #- name: Verify commit exists in origin/master
      #  run: |
      #    git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
      #    git branch --remote --contains | grep origin/master
          
      - name: Add nuget source
        run: |
          dotnet nuget add source --username binarycow --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/binarycow/index.json"

      - name: Build
        run: dotnet build --configuration Release NetworkPrimitives.sln
      - name: Test
        run: dotnet test --configuration Release --no-build NetworkPrimitives.sln
      - name: Pack
        run: dotnet pack --configuration Release --no-build --output . --include-symbols --include-source NetworkPrimitives.sln
      - name: Push
        run: dotnet nuget push NetworkPrimitives.*.*.nupkg --source github ${{ secrets.GITHUB_TOKEN }}
